version = 0.1
[default.deploy.parameters]
stack_name = "aws-bedrock-telegram-genai-chatbot-1"
resolve_s3 = true
s3_prefix = "aws-bedrock-telegram-genai-chatbot-1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
